### PR TITLE
Thud updates

### PR DESCRIPTION
**Pull request by balister**

### CODE REVIEW

**Comment by balister** [comment]
Ping. I'm using the mender partition size overrides in local.con so I can use a larger SD Card. Carrying them locally is a pain

**Comment by balister** [comment]
Pull request is getting confused but can you please merge the override partition size patch!

**Comment by joergho** [comment]
I merged your two changes regarding musl (ac33627790943a66731433ee3a944e87bfd5a5c1) and the mender partition size override (c56842a14abf7e1728060ba8e62f9a14f91cadf8).

The changes regarding UHD 3.14 make UHD and MPM compiling but there is a runtime issue that the sfp interfaces will not be detected because patch https://github.com/EttusResearch/meta-ettus/blob/thud/meta-ettus-core/recipes-kernel/linux/linux-yocto-4.18/0032-net-nixge-Make-mdio-child-node-optional.patch which is in place starting from thud / UHD 3.15.
It would have to be removed specifically for UHD 3.14 in https://github.com/EttusResearch/meta-ettus/blob/thud/meta-ettus-core/recipes-kernel/linux/linux-yocto-4.18/core.scc#L28.

**Comment by joergho** [comment]
BTW - UHD images download was improved recently: with b70f4ba4bf9785226ea187bdbf081e822bcb83f7 and 9ffe17a3d4a297e5dbbb88c00e95b68dbac766a4 (and following commits), the uhd-images-downloader is now used for downloading the correct FPGA images during OE build. It uses the images/manifest.txt file from the UHD repo. This removes the necessity for running the update_uhd.py script which was previously used to change all the different hashes in the various recipe files. Changing the UHD SRCREV is now sufficient for all (UHD, UHD FPGA images, default UHD FPGA image in firmware).

**Pull request closed without merging**
