### PR TITLE
Mbr0wn/rocko n3xx updates

### PR DESCRIPTION
**Pull request by mbr0wn**

### CODE REVIEW

**Review by mfischer — CHANGES_REQUESTED** [review]
In general I'd split up the commit, since it does two separate things.
I'd also probably introduce a MPM_DEVICE ?= "n3xx" variable in the usrp-hwd recipe, that I then override with MPM_DEVICE_ni-sulfur = "n3xx" or MPM_DEVICE_ni-neon = "banana".

**Review by mfischer — COMMENTED** [review]
This looks correct.

**Review by trungnob — COMMENTED** [review]
should the dts change as well?

**Review by mfischer — CHANGES_REQUESTED** [review]
The dts needs to change, too.

**Comment by mbr0wn** [comment]
Good catch, guysers.

**Comment by mbr0wn** [comment]
Updated all comments.

**Comment by mfischer** [comment]
Cherry-picked onto rocko/n3xx

**Pull request closed without merging**
